<?php

namespace Entity\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCustom(string $prenom)
    {
        $qb = $this->_em->createQueryBuilder();
        
        return $qb
            ->select('u, c')
            ->from('Entity\Utilisateur', 'u')
            ->join('u.civilite', 'c')
            ->where($qb->expr()->eq('u.prenom', ':prenom'))
            ->setParameter(':prenom', $prenom)
            ->getQuery()
            ->getResult();
    }
}
